// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://iqijmfgofbzmlkdjmkoh.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxaWptZmdvZmJ6bWxrZGpta29oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjY4NzgzNTksImV4cCI6MjA0MjQ1NDM1OX0.OypcGQ7NMDpeItrGRH5Nj9FyY0TXYuoktn7FmoKlZtk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);